import sqlite3
conn = sqlite3.connect('data/fact_layer.db')
c = conn.cursor()
c.execute('SELECT name FROM sqlite_master WHERE type="table"')
print('Tables:', c.fetchall())
c.execute('SELECT count(*) FROM documents')
print('Documents:', c.fetchone())
c.execute('SELECT count(*) FROM facts')
print('Facts:', c.fetchone())
c.execute('SELECT count(*) FROM fact_relationships')
print('Relationships:', c.fetchone())
c.execute('SELECT id, filename, status FROM documents')
print('Documents:', c.fetchall())